---
kind: pipeline
name: default

steps:
  - name: sync
    image: alpine/git:1.0.7
    commands:
      - ls

trigger:
  branch:
    - master

---
kind: pipeline
name: publish

steps:
  - name: publish
    image: rust:1.33-slim
    volumes:
      - name: cargo
        path: /root/.cargo
    commands:
      - sh -f /root/.cargo/credentials
      - cargo publish

volumes:
  - name: cargo
    host:
      path: /data/mount/cargo

trigger:
#  branch:
#    - master
  event:
    - tag


---
kind: pipeline
name: build

steps:
  - name: build
    image: rust:1.33-slim
    commands:
      - cargo test
      - cargo package

trigger:
  branch:
    - master
